package com.containermgmt.tfpeventingester.stream;

import com.containermgmt.tfpeventingester.model.EvtAssetDamage;
import com.containermgmt.tfpeventingester.model.EvtUnitDamageLabel;
import com.containermgmt.tfpeventingester.model.EvtVehicleDamageLabel;
import com.containermgmt.tfpeventingester.service.BerlinkLookupService;
import com.containermgmt.tfpeventingester.service.BerlinkLookupService.LookupResult;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.javalite.activejdbc.Model;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Processes messages from tfp-asset-damages-stream and persists them to
 * evt_asset_damages + evt_vehicle_damage_labels / evt_unit_damage_labels.
 */
@Component
@Slf4j
public class AssetDamageStreamProcessor extends AbstractStreamProcessor {

    /** Maps JSON tag → DB column for VEHICLE labels */
    private static final Map<String, String> VEHICLE_TAG_TO_COLUMN = Map.ofEntries(
        Map.entry("DMG_BRACKING", "dmg_braking"),
        Map.entry("DMG_TYRES", "dmg_tyres"),
        Map.entry("DMG_ISO_AIR", "dmg_iso_air"),
        Map.entry("DMG_LIGHT", "dmg_light"),
        Map.entry("DMG_TWIST_LOCK", "dmg_twist"),
        Map.entry("DMG_OTHER", "dmg_other"),
        Map.entry("DMG_PISTON", "dmg_piston"),
        Map.entry("DMG_STABILIZERS", "dmg_stabilizers"),
        Map.entry("DMG_CONTROL", "dmg_control"),
        Map.entry("DMG_ROLLER", "dmg_roller"),
        Map.entry("DMG_WORN_HOSE", "dmg_worn_hose")
    );


    private static final Map<String, String> UNIT_TAG_TO_COLUMN = Map.ofEntries(
        Map.entry("DMG_STRUCTURE", "dmg_structure"),
        Map.entry("DMG_DOORS", "dmg_doors"),
        Map.entry("DMG_ROOF", "dmg_roof"),
        Map.entry("DMG_WALLS", "dmg_walls"),
        Map.entry("DMG_TWIST_LOCK", "dmg_twist_lock"),
        Map.entry("DMG_OTHER", "dmg_other"),
        Map.entry("DMG_FLOOR", "dmg_floor"),
        Map.entry("DMG_SIDE_SHOT", "dmg_side_shot"),
        Map.entry("DMG_DOOR_HANDLES", "dmg_door_handles"),
        Map.entry("DMG_ZIPPERS", "dmg_zippers"),
        Map.entry("DMG_ROOF_SLATS", "dmg_roof_slats"),
        Map.entry("DMG_HOOKS", "dmg_hooks"),
        Map.entry("DMG_HATCHES", "dmg_hatches"),
        Map.entry("DMG_HANDRAIL", "dmg_handrail"),
        Map.entry("DMG_LETTERBOX", "dmg_letterbox"),
        Map.entry("DMG_SECURITY", "dmg_security")
    );


    public AssetDamageStreamProcessor(ObjectMapper objectMapper,
                                       BerlinkLookupService berlinkLookupService,
                                       @Value("${stream.asset-damages.key}") String streamKey,
                                       @Value("${stream.asset-damages.consumer-group}") String consumerGroup) {
        super(objectMapper, berlinkLookupService, streamKey, consumerGroup);
    }

    @Override
    protected Model buildModel(String messageId, String eventType, Map<String, Object> payload) {
        // Not used — buildModels() is overridden instead
        return null;
    }

    @Override
    @SuppressWarnings("unchecked")
    protected List<Model> buildModels(String messageId, String eventType, Map<String, Object> payload) {
        // Main model (ID generated by DB sequence — payload "id" is not required)
        EvtAssetDamage damage = new EvtAssetDamage();
        damage.set("message_id", messageId);
        damage.set("message_type", eventType);        
        damage.set("type", getString(payload, "type"));
        damage.set("status", getString(payload, "status"));
        damage.set("asset_id", getLong(payload, "assetId"));
        damage.set("edit_time", parseTimestamp(payload, "editTime"));
        damage.set("severity", getString(payload, "severity"));
        damage.set("asset_type", getString(payload, "assetType"));
        damage.set("asset_owner", getString(payload, "assetOwner"));
        damage.set("edit_user_id", getLong(payload, "editUserId"));
        damage.set("report_time", parseTimestamp(payload, "reportTime"));
        damage.set("closing_time", parseTimestamp(payload, "closingTime"));
        damage.set("description", getString(payload, "description"));
        damage.set("report_notes", getString(payload, "reportNotes"));
        damage.set("closing_user_id", getLong(payload, "closingUserId"));
        damage.set("asset_identifier", getString(payload, "assetIdentifier"));

        List<Model> models = new ArrayList<>(2);
        models.add(damage);

        // Label model (depends on assetType)
        String assetType = getString(payload, "assetType");
        List<Map<String, Object>> labels =
                (List<Map<String, Object>>) payload.get("assetDamageLabels");

        if (labels != null && !labels.isEmpty()) {
            Set<String> activeTags = extractActiveTags(labels);

            if ("VEHICLE".equalsIgnoreCase(assetType)) {
                models.add(buildVehicleLabel(null, activeTags));
            } else if ("UNIT".equalsIgnoreCase(assetType)) {
                models.add(buildUnitLabel(null, activeTags));
            }
        }

        return models;
    }

    private Set<String> extractActiveTags(List<Map<String, Object>> labels) {
        Set<String> tags = new HashSet<>();
        for (Map<String, Object> label : labels) {
            Object tag = label.get("tag");
            if (tag != null && "true".equalsIgnoreCase(String.valueOf(label.get("value")))) {
                tags.add(tag.toString());
            }
        }
        return tags;
    }

    private EvtVehicleDamageLabel buildVehicleLabel(Long idAssetDamage, Set<String> activeTags) {
        EvtVehicleDamageLabel label = new EvtVehicleDamageLabel();
        label.set("id_asset_damage", idAssetDamage);
        for (Map.Entry<String, String> entry : VEHICLE_TAG_TO_COLUMN.entrySet()) {
            label.set(entry.getValue(), activeTags.contains(entry.getKey()));
        }
        return label;
    }

    private EvtUnitDamageLabel buildUnitLabel(Long idAssetDamage, Set<String> activeTags) {
        EvtUnitDamageLabel label = new EvtUnitDamageLabel();
        label.set("id_asset_damage", idAssetDamage);
        for (Map.Entry<String, String> entry : UNIT_TAG_TO_COLUMN.entrySet()) {
            label.set(entry.getValue(), activeTags.contains(entry.getKey()));
        }
        return label;
    }

    // --- Save override: propagate parent's generated ID to labels ---

    @Override
    protected void saveModels(List<Model> models, LookupResult lookup) {
        Model parent = models.get(0); // EvtAssetDamage is always first
        if (lookup.hasData()) {
            parent.set("container_number", lookup.containerNumber());
            parent.set("id_trailer", lookup.idTrailer());
            parent.set("id_vehicle", lookup.idVehicle());
        }
        parent.saveIt();
        Object actualId = parent.getId();
        log.info("Saved parent EvtAssetDamage: generated id_asset_damage={}", actualId);

        // Propagate the actual DB-generated ID to label models
        for (int i = 1; i < models.size(); i++) {
            models.get(i).set("id_asset_damage", actualId);
            models.get(i).saveIt();
        }
    }

    // --- BERLink lookup overrides ---

    @Override
    protected String getUnitNumberFromPayload(Map<String, Object> payload) {
        return getString(payload, "assetIdentifier");
    }

    @Override
    protected String getUnitTypeCodeFromPayload(Map<String, Object> payload) {
        String assetType = getString(payload, "assetType");
        // TFP uses "UNIT" for containers, BERLink expects "CONTAINER"
        if ("UNIT".equalsIgnoreCase(assetType)) {
            return "CONTAINER";
        }
        return assetType;
    }

    // --- Dedup & resend ---

    @Override
    protected boolean existsByMessageId(String messageId) {
        return EvtAssetDamage.existsByMessageId(messageId);
    }

    @Override
    protected int deleteByMessageId(String messageId) {
        // Cascade: delete associated labels before the main record
        EvtAssetDamage existing = EvtAssetDamage.findByMessageId(messageId);
        if (existing != null) {
            long idAssetDamage = ((Number) existing.getId()).longValue();
            EvtVehicleDamageLabel.deleteByAssetDamageId(idAssetDamage);
            EvtUnitDamageLabel.deleteByAssetDamageId(idAssetDamage);
        }
        return EvtAssetDamage.deleteByMessageId(messageId);
    }

    @Override
    protected String processorName() {
        return "asset damage";
    }
}
