version: '3'

tasks:

  stop-vui:
    cmds:
      - docker-compose -f docker-compose.yml stop valkey-ui
    silent: true

  build-vui:
    cmds:
      - docker-compose -f docker-compose.yml build valkey-ui
    silent: true

  vui:
    cmds:
      - task stop-vui
      - task build-vui
    silent: true

  logs-vui:
    cmds:
      - docker-compose logs -f valkey-ui

  up:
    cmds:
      - docker-compose -f docker-compose.yml up -d
    silent: true

  restart:
    cmds:
      - docker-compose down && docker-compose -f docker-compose.yml up -d
    silent: true
